# Generated by Django 5.1.1 on 2024-09-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(default=2000),
        ),
    ]
